default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: <%= ENV['DEV_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: ElClub_development


test:
  <<: *default
  database: ElClub_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is

#
production:
  <<: *default
  # encoding: unicode
  pool: 25
  database: elclub_production
  username: <%= ENV['BOXFUL_POSTGRES_USER'] %>
  password: <%= ENV['BOXFUL_POSTGRES_PASSWORD'] %>
