


default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: <%= ENV['DEV_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
development:
  <<: *default
  database: manta_development
test:
  <<: *default
  database: manta_test
# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is


# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is

#
production:
  <<: *default
  # encoding: unicode
  pool: 25
  database: manta_production
  username: manta
  password: <%= ENV['MANTA_POSTGRES_PASSWORD'] %>
